---

- name: Symlink git configs
  file:
      src: "{{ role_path }}/{{ item.path }}"
      dest: "{{ ansible_env.HOME }}/{{ item.name }}"
      state: link
      force: yes
  with_items:
      - {path: "files/.gitconfig", name: ".gitconfig"}
      - {path: "files/.gitignore_global", name: ".gitignore_global"}
