---

- name: Symlink emacs configs
  file:
      src: "{{ role_path }}/{{ item.path }}"
      dest: "{{ ansible_env.HOME }}/{{ item.name }}"
      state: link
      force: yes
  with_items:
      - {path: "files/.spacemacs", name: ".spacemacs"}
      - {path: "files/snippets", name: ".emacs.d/snippets"}

- name: Install emacs
  package: name=emacs state=present
  become: true

- name: Clone spacemacs
  git:
      repo: https://github.com/syl20bnr/spacemacs
      dest: "{{ spacemacs_path }}"
