---
- hosts: all
  vars:
      HOME_PATH: "{{ ansible_env.HOME }}"
      BIN_PATH: "{{ ansible_env.HOME }}/local/.bin"
      ZPLUG_PATH: "{{ ansible_env.HOME }}/.zplug"
      BASH_IT_PATH: "{{ ansible_env.HOME }}/.bash_it"
      GIT_NUMBER_PATH: "{{ ansible_env.HOME }}/git-number"
      SPACEMACS_PATH: "{{ ansible_env.HOME }}/.emacs.d"
      TPM_PATH: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
      FZF_PATH: "{{ ansible_env.HOME }}/.fzf"

  roles:
      - role: geerlingguy.git
        git_packagese:
            - git
        tags: git
        become: true
      - role: howtodojo.tmux
        tags: tmux
        become: true
      - role: theNewFlesh.tree
        tags: tree
        become: true
      - role: ngpestelos.fasd
        tags: fasd
        become: true

  tasks:
      - name: Create user bin directory
        file:
            path: "{{ BIN_PATH }}"
            state: directory

      - name: Install zplug
        git:
            repo: https://github.com/zplug/zplug
            dest: "{{ ZPLUG_PATH }}"
        tags: zsh

      - name: Install bash-it
        git:
            repo: https://github.com/Bash-it/bash-it
            dest: "{{ BASH_IT_PATH }}"
        tags: bash

      - name: Clone spacemacs
        git:
            repo: https://github.com/syl20bnr/spacemacs
            dest: "{{ SPACEMACS_PATH }}"
        tags:
            - emacs
            - spacemacs

      - name: Symlink dotfiles
        file:
            src: "{{ playbook_dir }}/../{{ item.path }}"
            dest: "{{ HOME_PATH }}/{{ item.name }}"
            state: link
            force: yes
        with_items:
            - {path: "shells/.bashrc", name: ".bashrc"}
            - {path: "shells/.zshrc", name: ".zshrc"}
            - {path: "shells/.aliases", name: ".aliases"}
            - {path: "git/.gitconfig", name: ".gitconfig"}
            - {path: "git/.gitignore_global", name: ".gitignore_global"}
            - {path: "other/.tmux.conf", name: ".tmux.conf"}
            - {path: "other/.fasdrc", name: ".fasdrc"}
            - {path: "other/.ctags", name: ".ctags"}
            - {path: "editors/vim/.vimrc", name: ".vimrc"}
            - {path: "editors/vim/.vim", name: ".vim"}
            - {path: "editors/emacs/.spacemacs", name: ".spacemacs"}
            - {path: "editors/emacs/snippets", name: ".emacs.d/snippets"}
            - {path: "file_managers/vifm/vifmrc", name: ".vifm/vifmrc"}
            - {path: "other/gpg.conf", name: ".gnupg/gpg.conf"}
            - {path: "other/psysh.php", name: ".config/psysh/config.php"}
            - {path: "shells/.autolaunch_tmux", name: ".autolaunch_tmux"}
            - {path: "shells/.launch_jetbrains_terminal", name: ".launch_jetbrains_terminal"}

      - name: Check if vim plugins are installed
        stat:
            path: "{{ playbook_dir }}/../editors/vim/.vim/bundle/vim-pathogen/.git"
        register: vim_plugins

      - name: Install vim plugins
        command: git submodule update --init
        args:
            chdir: "{{ playbook_dir }}/.."
        when: vim_plugins.stat.isdir is defined and vim_plugins.stat.isdir
        tags: vim

      - name: Clone git-number
        git:
           repo: https://github.com/holygeek/git-number
           dest: "{{ GIT_NUMBER_PATH }}"

      - name: Symlink git-number files
        file:
           src: "{{ GIT_NUMBER_PATH }}/{{ item.name }}"
           dest: "{{ BIN_PATH }}/{{ item.name }}"
           state: link
           force: yes
        with_items:
           - {name: "git-number"}
           - {name: "git-list"}
           - {name: "git-id"}
        tags: git-number

      - name: Install emacs
        package: name=emacs state=present
        become: true
        tags: emacs

      - name: Clone tmux-plugin-manager
        git:
            repo: https://github.com/tmux-plugins/tpm
            dest: "{{ TPM_PATH }}"
        tags: tmux

      - name: Install httpie
        package: name=httpie state=present
        become: true
        tags: httpie

      - name: Clone fzf
        git:
            repo: https://github.com/junegunn/fzf
            dest: "{{ FZF_PATH }}"
            depth: 1
        tags: fzf

      - name: Install fzf
        shell: "bash {{ FZF_PATH }}/install --all"
        args:
            chdir: "{{ HOME_PATH }}"
            creates: "{{ HOME_PATH }}/.fzf.zsh"
        tags: fzf

