---

- name: Symlink gpg configs
  file:
      src: "{{ role_path }}/{{ item.path }}"
      dest: "{{ ansible_env.HOME }}/{{ item.name }}"
      state: link
      force: yes
  with_items:
      - {path: "files/gpg.conf", name: ".gnupg/gpg.conf"}
